name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck --checks all,-ST1020,-ST1000,-ST1003 ./...

    - name: Build
      run: go build cmd

    - name: Test
      run: |
        go mod tidy
        go install github.com/rakyll/gotest@latest
        gotest ./...

    # - name: Coverage
    #   uses: gwatts/go-coverage-action@v1.1.2
    #   with:
    #     coverage-threshold: 85
