name: Package JSON Lint

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  package-json-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npx --yes npm-package-json-lint@9.0.0 .
