name: Verify Tokens and Vaults

on:
    push:
    pull_request:

jobs:
    verify:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Verify Tokens
              run: bun run scripts/verify-tokens.js

            - name: Verify Vaults
              run: bun run scripts/verify-vaults.js
